name: Deploy to GitHub Pages

on:
  push:
    branches:
      - include_name_on_signup # branch to deploy from

jobs:
  build:
    environment: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # or the version your project uses

      - name: Install dependencies
        run: npm install

      - name: Fix Stripe Types
        run: node fix-stripe-types.js

      - name: Build the project
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
